# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

10000


### Encoding categorical data

Label Encoding the "Gender" column

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [12]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [17]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [19]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [23]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [24]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 391us/sample - loss: 0.5017 - accuracy: 0.7926
Epoch 2/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.4521 - accuracy: 0.7961
Epoch 3/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.4370 - accuracy: 0.7971
Epoch 4/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.4247 - accuracy: 0.8050
Epoch 5/100
8000/8000 [==============================] - 1s 86us/sample - loss: 0.4117 - accuracy: 0.8196
Epoch 6/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.3996 - accuracy: 0.8309
Epoch 7/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3890 - accuracy: 0.8355
Epoch 8/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3797 - accuracy: 0.8376
Epoch 9/100
8000/8000 [==============================] - 1s 87us/sample - loss: 0.3724 - accuracy: 0.8415
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 111us/sample - loss: 0.3385 - accuracy: 0.8622
Epoch 78/100
8000/8000 [==============================] - 1s 104us/sample - loss: 0.3384 - accuracy: 0.8622
Epoch 79/100
8000/8000 [==============================] - 1s 90us/sample - loss: 0.3384 - accuracy: 0.8633
Epoch 80/100
8000/8000 [==============================] - 1s 84us/sample - loss: 0.3382 - accuracy: 0.8633
Epoch 81/100
8000/8000 [==============================] - 1s 93us/sample - loss: 0.3380 - accuracy: 0.8626
Epoch 82/100
8000/8000 [==============================] - 1s 101us/sample - loss: 0.3380 - accuracy: 0.8614 - loss: 0.328
Epoch 83/100
8000/8000 [==============================] - 1s 95us/sample - loss: 0.3381 - accuracy: 0.8634
Epoch 84/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.3382 - accuracy: 0.8625
Epoch 85/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.3379 - accuracy: 0.8631
Epoch 86/100
8000/8000 [=========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [41]:
C = [[1][2][3]]
D = [[4][5][6]]
print(np.concatenate((C,D),1))

IndexError: list index out of range

In [42]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1508   87]
 [ 198  207]]
